language: java
jdk:
  - openjdk8
services:
  - docker
before_install:
  - sudo service mysql stop
branches:
  only:
    - master
install: mvn -B clean install -Dgpg.skip=true -Dmaven.test.skip=true -Dmaven.javadoc.skip=true
script: mvn cobertura:cobertura
after_success:
  - bash <(curl -s https://codecov.io/bash)
